###        ‹€€€€€   ‹
###      ∞€€€€ ﬂ€€ €≤ ﬂﬂﬂ€€€€€€€‹     ﬂﬂﬂﬂﬂ€€≤€€‹     ‹≤€€€ﬂ
###     ±€€€ﬂ   ±€€ﬂ        ﬂﬂ€€€€∞           ﬂ€€€  ±€€€ﬂ
###    ≤€€€      ﬂ         €€≤  ﬂ€€€±           ∞€€≤€€€
###   ≤€€€        ‹€€€€€‹  €€€   ﬂ€€€ ‹€€€€€€‹  ±€€€€€
###   €€€∞     ∞€€€€ﬂ  ﬂ€≤ €€€    €€€≤€€≤  ∞€€  €€€≤€€€
###   ±€€€     €€€€∞    €€ €€€   ∞€€€€€€€€€€€ﬂ €€€± ±€€€
###    ∞€€€‹ ‹€€ﬂ≤€€‹ ‹€€ ≤€€   €€€±€€€∞     ‹€€€∞   ∞€€€‹
###      ﬂ€€€€€ﬂ   ﬂ€€€≤ﬂ  €€ﬂ ∞€€€∞  ﬂ€€€€€€€≤€ﬂ       ﬂ≤€€‹
###                        ‹€€€€€€±
###          ﬂﬂﬂ€€≤‹‹‹‹‹€≤€€€≤ﬂﬂ    
###
###
### Game data is stored at %SystemDrive%\Users\Public\Documents\Steam\CODEX\221680
###

[Settings]
###
### Game identifier (http://store.steampowered.com/app/221680)
###
AppId=221680
###
### Steam Account ID, set it to 0 to get a random Account ID
###
#AccountId=0
### 
### Name of the current player
###
UserName=Player
###
### Language that will be used in the game
###
Language=english
###
### Enable lobby mode
###
LobbyEnabled=1
###
### Lobby port to listen on
###
#LobbyPort=31183
###
### Enable/Disable Steam overlay
###
Overlays=1
###
### Set Steam connection to offline mode
###
Offline=1
###
SelfProtect=0

[Interfaces]
###
### Steam Client API interface versions
###
SteamAppList=STEAMAPPLIST_INTERFACE_VERSION001
SteamApps=STEAMAPPS_INTERFACE_VERSION008
SteamClient=SteamClient017
SteamController=SteamController007
SteamFriends=SteamFriends017
SteamGameServer=SteamGameServer013
SteamGameServerStats=SteamGameServerStats001
SteamHTMLSurface=STEAMHTMLSURFACE_INTERFACE_VERSION_005
SteamHTTP=STEAMHTTP_INTERFACE_VERSION003
SteamInput=SteamInput001
SteamInventory=STEAMINVENTORY_INTERFACE_V003
SteamMatchGameSearch=SteamMatchGameSearch001
SteamMatchMaking=SteamMatchMaking009
SteamMatchMakingServers=SteamMatchMakingServers002
SteamMusic=STEAMMUSIC_INTERFACE_VERSION001
SteamMusicRemote=STEAMMUSICREMOTE_INTERFACE_VERSION001
SteamNetworking=SteamNetworking006
SteamParentalSettings=STEAMPARENTALSETTINGS_INTERFACE_VERSION001
SteamParties=SteamParties002
SteamRemotePlay=STEAMREMOTEPLAY_INTERFACE_VERSION001
SteamRemoteStorage=STEAMREMOTESTORAGE_INTERFACE_VERSION014
SteamScreenshots=STEAMSCREENSHOTS_INTERFACE_VERSION003
SteamUGC=STEAMUGC_INTERFACE_VERSION014
SteamUser=SteamUser020
SteamUserStats=STEAMUSERSTATS_INTERFACE_VERSION011
SteamUtils=SteamUtils009
SteamVideo=STEAMVIDEO_INTERFACE_V002
###

[DLC]
###
### Automatically unlock all DLCs
###
DLCUnlockall=1
###
### Identifiers for DLCs
###
#ID=Name
248750=RocksmithÆ 2014 - The Smashing Pumpkins - ìCherub Rockî
###

[Crack]
9a3b8fe70a980452=b7d5bc716512b5d6
e2105ecafa22c6c3=b7d5bc716512b5d6
